#! /bin/sh

if [ ! -e build.ninja ]; then
	echo "build.ninja not found in current folder"
	exit 1
fi

tools=$(dirname "$0")
root=$(realpath "$tools/..")
inotify-hookable  --watch-directories "$root" --ignore-paths "$root/build" --on-modify-command "ninja" "$@"
